export const CHANGE_TRIP_NAME = 'CHANGE_TRIP_NAME'
export const CHANGE_LOCATION = 'CHANGE_LOCATION'
export const CHANGE_START_DATE = 'CHANGE_START_DATE'
export const CHANGE_END_DATE = 'CHANGE_END_DATE'